# Generated by Django 2.2.24 on 2022-01-12 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0003_auto_20220112_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
