# Generated by Django 2.2.24 on 2022-01-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0004_remove_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
